services:
  mysql:
    image: mysql:5.7
    container_name: renovation-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: renovation_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    restart: unless-stopped